(function(c,b){function u(a){for(var c={},e,d,f=0;f<a.length;f++)d=a[f],e=d.r+d.s+d.m,d.c&&(c[e]||(c[e]=[]),c[e].push(a[f]));return c}function m(a){for(var c=1;c<arguments.length;c++){var e=arguments[c];try{if(e.isSupported)return e.send(a)}catch(d){}}}function w(){if(f.length){for(var c=0;c<h.length;c++)h[c]();a._flhs+=1;l();m(u(f.splice(0,f.length)),G,J,E)}M=H=0}function l(){I&&n({k:"chk",f:a._flhs,l:a._lpn,s:"full"},"csm")}function n(d,p,e){e=e||{};!c.ue_furl||0===e.bf&&a.isBF||(d={r:e.r||a.rid,
s:e.s||c.ue_sid,m:e.m||c.ue_mid,mkt:e.mkt||c.ue_mkt,sn:e.sn||c.ue_sn,c:p,d:d,t:e.t||a.d(),cs:e.c&&c.ue_qsl},a._lpn[p]=(a._lpn[p]||0)+1,e.b?m(u([d]),G,E):e.nb?m(u([d]),G,J,E):e.img||P[p]?m(u([d]),E):e.ff?(f.push(d),w()):e.n?(f.push(d),0===Q?w():M||(M=b.setTimeout(w,Q))):(f.push(d),H||(H=b.setTimeout(w,R))))}function k(a,c,e){F++;F==O&&n({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},b.ue_err_chan||"jserr");(F<O||e&&e.il)&&n(a,c,e)}function x(){if(!N){for(var c=0;c<
d.length;c++)d[c]();for(c=0;c<h.length;c++)h[c]();a._flhs+=1;l();m(u(f.splice(0,f.length)),G,E);N=!0}}var A={};(function(){function a(c){return 10>c?"0"+c:c}function c(a){d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var c=h[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(a,d){var g,r,h,q,v=f,D,l=d[a];l&&"object"===typeof l&&"function"===typeof l.toJSON&&(l=l.toJSON(a));"function"===typeof k&&(l=k.call(d,a,l));switch(typeof l){case "string":return c(l);
case "number":return isFinite(l)?String(l):"null";case "boolean":case "null":return String(l);case "object":if(!l)return"null";f+=b;D=[];if("[object Array]"===Object.prototype.toString.apply(l)){q=l.length;for(g=0;g<q;g+=1)D[g]=e(g,l)||"null";h=0===D.length?"[]":f?"[\n"+f+D.join(",\n"+f)+"\n"+v+"]":"["+D.join(",")+"]";f=v;return h}if(k&&"object"===typeof k)for(q=k.length,g=0;g<q;g+=1)"string"===typeof k[g]&&(r=k[g],(h=e(r,l))&&D.push(c(r)+(f?": ":":")+h));else for(r in l)Object.prototype.hasOwnProperty.call(l,
r)&&(h=e(r,l))&&D.push(c(r)+(f?": ":":")+h);h=0===D.length?"{}":f?"{\n"+f+D.join(",\n"+f)+"\n"+v+"}":"{"+D.join(",")+"}";f=v;return h}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(c){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});
var d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,b,h={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},k;"function"!==typeof A.stringify&&(A.stringify=function(a,c,d){var g;b=f="";if("number"===typeof d)for(g=0;g<d;g+=1)b+=" ";else"string"===typeof d&&(b=d);if((k=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return e("",{"":a})})})();
var y=function(){function a(c,e){if(null==c)return e.push("!n");if("number"===typeof c)return e.push("!"+c);if("string"===typeof c)return"\\"==c[c.length-1]?e.push("'"+c.replace(/'/g,"\\'")+"u005C'"):e.push("'"+c.replace(/'/g,"\\'")+"'");if("boolean"===typeof c)return e.push(c?"!t":"!f");if(c instanceof Array){e.push("*");for(var d=0;d<c.length;d++)a(c[d],e);return e.push(")")}if("object"==typeof c){e.push("(");for(d in c)c.hasOwnProperty(d)&&(e.push(d),a(c[d],e));return e.push(")")}return e.push("!n")}
return{stringify:function(c){var e=[];a(c,e);return e.join("")}}}(),B=c.ue_qsl||2E3,O=2E3,I=1===window.ue_ddq,t=function(){},z=b.JSON&&b.JSON.stringify||A&&A.stringify,K=y.stringify,a=c.ue||{},y=c.uet||t;(c.uet||t)("bb","ue_frst_v2",{wb:1});var q="//"+c.ue_furl+"/1/batch/1/OE/",f=[],d=[],h=[],N=!1,M,H,Q=void 0===c.ue_hpfi?1E3:c.ue_hpfi,R=void 0===c.ue_lpfi?1E4:c.ue_lpfi,P={"scheduled-delivery":1},F=0,J=function(){function d(){if(b.XDomainRequest){var a=new XDomainRequest;a.onerror=t;a.ontimeout=t;
a.onprogress=t;a.onload=t;a.timeout=0;return a}if(b.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(b.ActiveXObject){for(var c=0;c<g.length&&!a;c++)try{a=new ActiveXObject(g[c]),g=[g[c]]}catch(e){}return a}}function p(e){for(var d=[],g=e[0]||{},f=0;f<e.length;f++){var p={};p[e[f].c]=e[f].d;d.push(p)}return{rid:g.r||a.rid,sid:g.s||c.ue_sid,mid:g.m||c.ue_mid,mkt:g.mkt||c.ue_mkt,sn:g.sn||c.ue_sn,reqs:d}}function e(a){var c=p(a),e=d();if(!e)throw"";e.onerror=function(){for(var c=
0;c<a.length;c++)f.push(a[c]);J.isSupported=!1};e.open("POST",q,!0);e.setRequestHeader&&e.setRequestHeader("Content-type","text/plain");e.send(z(c))}var g="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var c in a)a.hasOwnProperty(c)&&a[c].length&&e(a[c])},buildPOSTBodyLog:p,isSupported:!0}}(),E=function(){return{send:function(d){for(var f in d)if(d.hasOwnProperty(f)){for(var e=d[f],g=e,b={},h=void 0,
k=0;k<g.length;k++)h=g[k].c,b[h]||(b[h]=[]),b[h].push(g[k]);var e=e[0]||{},g=e.sn||c.ue_sn,e=q+(e.m||c.ue_mid)+":"+(e.s||c.ue_sid)+":"+(e.r||a.rid)+(g?":"+g:""),g=[],h=e,k=[],v=void 0;for(v in b)if(b.hasOwnProperty(v))for(var l=0;l<b[v].length;l++){var n=b[v][l],t=encodeURIComponent((n.cs?K:z)(n.d));k.push({l:t,t:n.t,p:1,c:v,d:n.cs?"c":"j"})}b=k;k=void 0;v="$";for(n=0;n<b.length;){l=b[n];k!=l.c?(h+=v+l.c+"=",v="&",k=l.c):h+=",";var t=h,m=l.d+":",x=l,h=(x.l.match(".{1,"+(B-h.length)+"}[^%]{0,2}")||
[])[0]||"";x.l=x.l.substr(h.length);h=t+(m+h+":"+l.t);if(l.l)h+=":"+l.p++ +"_",g.push(h),h=e,v="$",k=0;else if(n++,1!=l.p)for(h+=":"+l.p+"_"+l.p,t=0;t<l.p-1;t++)g[g.length-t-1]+=l.p}g.push(h);e=g;for(g=0;g<e.length;g++)(new Image).src=e[g]}},isSupported:!0}}(),G=function(){return{send:function(a){for(var c in a)if(a.hasOwnProperty(c)){var e=J.buildPOSTBodyLog(a[c]);if(!navigator.sendBeacon(q,z(e)))throw"";}},isSupported:!!navigator.sendBeacon}}();a._fic=E;a._fac=J;a._fbc=G;a._flq=f;a.sid=a.sid||c.ue_sid;
a.mid=a.mid||c.ue_mid;a.furl=a.furl||c.ue_furl;a.sn=a.sn||c.ue_sn;a._flhs=a._flhs||0;a._lpn=a._lpn||{};try{b.amznJQ&&b.amznJQ.declareAvailable&&b.amznJQ.declareAvailable("forester-client"),b.P&&b.P.register&&b.P.register("forester-client",t)}catch(v){c.ueLogError(v,{logLevel:"WARN"})}(function(){a.log&&a.log.isStub&&(a.log.replay(function(a,c,e){var d=a[2]||{};d.t=c;d.r=e;d.n=1;k(a[0],a[1],d)}),a.onunload.replay(function(a){d.push(a[0])}),a.onflush.replay(function(a){h.push(a[0])}))})();a.log=k;a.log.reset=
function(){F=0};a.onunload=function(a){d.push(a)};a.onflush=function(a){h.push(a)};a.attach("beforeunload",x);a.attach("pagehide",x);y("ld","ue_frst_v2",{wb:1})})(ue_csm,window);
(function(c,b){function u(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function m(a,b){if(!a)return{};var f="INFO"===b.logLevel;a.m&&a.m.message&&(a=a.m);var d=b.m||b.message||"",d=a.m&&a.m.message?d+a.m.message:a.m&&a.m.target&&a.m.target.tagName?d+("Error handler invoked by "+a.m.target.tagName+" tag"):a.m?d+a.m:a.message?d+a.message:d+"Unknown error",d={m:d,name:a.name,type:a.type,csm:O+" "+(a.fromOnError?"onerror":"ueLogError")},h,k,l=0,n;d.logLevel=b.logLevel||x;b.adb&&(d.adb=b.adb);if(h=b.attribution)d.attribution=
""+h;if(!f){d.pageURL=b.pageURL||""+(window.location?window.location.href:"")||"missing";d.f=a.f||a.sourceURL||a.fileName||a.filename||a.m&&a.m.target&&a.m.target.src;d.l=a.l||a.line||a.lineno||a.lineNumber;d.c=a.c?""+a.c:a.c;d.s=[];d.t=c.ue.d();if((f=a.stack||(a.err?a.err.stack:""))&&f.split)for(d.csm+=" stack",h=f.split("\n");l<h.length&&d.s.length<I;)(f=h[l++])&&d.s.push(u(f));else for(d.csm+=" callee",k=w(a.args||arguments,"callee"),h=l=0;k&&l<I;)n=t,k.skipTrace||(f=k.toString())&&f.substr&&(n=
0===h?4*t:n,n=1==h?2*t:n,d.s.push(f.substr(0,n)),h++),k=w(k,"caller"),l++;if(!d.f&&0<d.s.length&&(l=d)&&l.s){var m,f=0<l.s.length?l.s[0]:"";h=1<l.s.length?l.s[1]:"";f&&(m=f.match(K));m&&3==m.length||!h||(m=h.match(z));m&&3==m.length&&(l.f=m[1],l.l=m[2])}}return d}function w(a,c){try{return a[c]}catch(f){}}function l(a,l){if(a){var f=m(a,l),d=window.ue_err?window.ue_err.addContextInfo:null;d&&d(f);c.ue.log(f,l.channel||k,{nb:1});"function"===typeof ue_err.elh&&ue_err.elh(a,l);try{if(!a.fromOnError){var h=
b.console,n=b.JSON,d="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(h){if(n&&n.stringify)try{d+=n.stringify(f)}catch(t){d+="no info provided; converting to string failed"}else d+=f.m;"function"===typeof h.error?h.error(d,f):"function"===typeof h.log&&h.log(d,f)}}}catch(x){}}}function n(a,b){if(a&&!(c.ue_err.ec>c.ue_err.mxe)){c.ue_err.ter.push(a);b=b||{};var f=a.logLevel||b.logLevel;b.logLevel=f;b.attribution=a.attribution||b.attribution;f&&f!==
x&&f!==A&&f!==y&&f!==B||c.ue_err.ec++;f&&f!=x||ue_err.ecf++;l(a,b)}}if(c.ue_err&&(!c.ueLogError||c.ueLogError.isStub)){var k=c.ue_err_chan||"jserr",x="FATAL",A="ERROR",y="WARN",B="DOWNGRADED",O="v5",I=20,t=256,z=/\(?([^\s]*):(\d+):\d+\)?/,K=/.*@(.*):(\d*)/;l.skipTrace=1;m.skipTrace=1;n.skipTrace=1;(function(){if(c.ue_err.erl){var a=c.ue_err.erl.length,b,f;for(b=0;b<a;b++)f=c.ue_err.erl[b],l(f.ex,f.info);ue_err.erl=[]}})();c.ueLogError=n}})(ue_csm,window);
ue_csm.ue.exec(function(c,b){var u=function(){},m=function(){return{send:function(c,n){if(n&&c){var k;if(b.XDomainRequest)k=new XDomainRequest,k.onerror=u,k.ontimeout=u,k.onprogress=u,k.onload=u,k.timeout=0;else if(b.XMLHttpRequest){if(k=new XMLHttpRequest,!("withCredentials"in k))throw"";}else k=void 0;if(!k)throw"";k.open("POST",c,!0);k.setRequestHeader&&k.setRequestHeader("Content-type","text/plain");k.send(n)}},isSupported:!0}}(),w=function(){return{send:function(b,n){if(b&&n)if(navigator.sendBeacon(b,
n))c.ue_sbuimp&&c.ue&&c.ue.ssw&&c.ue.ssw("eelsts","scs");else throw"";},isSupported:!!navigator.sendBeacon&&!(b.cordova&&b.cordova.platformId&&"ios"==b.cordova.platformId)}}();c.ue._ajx=m;c.ue._sBcn=w},"Transportation-clients")(ue_csm,window);
ue_csm.ue.exec(function(c,b){function u(){for(var a=0;a<arguments.length;a++){var c=arguments[a];try{var e;if(c.isSupported){var f=p.buildPayload(N,d);e=c.send(q,f)}else throw dummyException;return e}catch(r){}}K({m:"All supported clients failed",attribution:"CSMSushiClient_TRANSPORTATION_FAIL",f:"sushi-client.js",logLevel:"ERROR"},b.ue_err_chan||"jserr")}function m(){if(d.length){for(var a=0;a<F.length;a++)F[a]();u(z._sBcn||{},z._ajx||{});d=[];h={};N={};E=G=M=H=0}}function w(){var a=new Date,c=function(a){return 10>
a?"0"+a:a};return Date.prototype.toISOString?a.toISOString():a.getUTCFullYear()+"-"+c(a.getUTCMonth()+1)+"-"+c(a.getUTCDate())+"T"+c(a.getUTCHours())+":"+c(a.getUTCMinutes())+":"+c(a.getUTCSeconds())+"."+String((a.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}function l(a){try{return JSON.stringify(a)}catch(c){}return null}function n(a){try{return JSON.parse(a)}catch(c){}return null}function k(a,e,f,h){var k=!1;h=h||{};R++;R==B&&K({m:"Max number of Sushi Logs exceeded",f:"sushi-client.js",
logLevel:"ERROR",attribution:"CSMSushiClient_MAX_CALLS"},b.ue_err_chan||"jserr");var q;if(q=!(R>=B))(q=a&&-1<a.constructor.toString().indexOf("Object")&&e&&-1<e.constructor.toString().indexOf("String")&&f&&-1<f.constructor.toString().indexOf("String"))||Q++;q&&(a.producerId=a.producerId||e,a.schemaId=a.schemaId||f,a.timestamp=w(),e=Date.now?Date.now():+new Date,a.messageId=c.ue_id+"-"+e+"-"+R,h&&!h.ssd&&(a.sessionId=a.sessionId||c.ue_sid,a.requestId=a.requestId||c.ue_id,a.obfuscatedMarketplaceId=
a.obfuscatedMarketplaceId||c.ue_mid),(e=l(a))?(e=e.length,(d.length==O||M+e>I)&&m(),M+=e,a={data:p.compressEvent(a)},d.push(a),(h||{}).n?0===v?m():E||(E=b.setTimeout(m,v)):G||(G=b.setTimeout(m,r)),k=!0):k=!1);!k&&c.ue_int&&console.error("Invalid JS Nexus API call");return k}function x(){if(!J){for(var a=0;a<P.length;a++)P[a]();for(a=0;a<F.length;a++)F[a]();d.length&&(c.ue_sbuimp&&c.ue&&c.ue.ssw&&(a=l({dct:N,evt:d}),c.ue.ssw("eeldata",a),c.ue.ssw("eelsts","unk")),u(z._sBcn||{}));J=!0}}function A(a){P.push(a)}
function y(a){F.push(a)}var B=1E3,O=499,I=524288,t=function(){},z=c.ue||{},K=z.log||t,a=c.uex||t;(c.uet||t)("bb","ue_sushi_v1",{wb:1});var q=c.ue_surl||"https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.gamma",f=["messageId","timestamp"],d=[],h={},N={},M=0,H=0,Q=0,R=0,P=[],F=[],J=!1,E,G,v=void 0===c.ue_hpsi?1E3:c.ue_hpsi,r=void 0===c.ue_lpsi?1E4:c.ue_lpsi,p=function(){function a(c){h[c]||(h[c]="#"+H++,N[h[c]]=c);return h[c]}function c(a){if(a)switch(typeof a){case "number":return!(isNaN(a)||
Infinity===a)&&a.toString().length>("#"+H).length;case "boolean":break;case "string":return a.length>("#"+H).length;default:return!0}return!1}function e(d){if(c(d)){var b=0;d instanceof Array?b=2:d instanceof Function?b=0:d instanceof Object&&(b=1);switch(b){case 0:d=a(d);break;case 2:var p=d;d=[];for(var b=p.length,r=0;r<b;r++)d[r]=e(p[r]);break;case 1:b={};for(p in d)d.hasOwnProperty(p)&&(b[a(p)]=-1==f.indexOf(p)?e(d[p]):d[p]);d=b}}return d}return{compressEvent:e,buildPayload:function(){return l({cs:{dct:N},
events:d})}}}();(function(){if(z.event&&z.event.isStub){if(c.ue_sbuimp&&c.ue&&c.ue.ssw&&c.ue.ssw("eeldata")){var a=n(c.ue.ssw("eeldata").val);a&&a.evt instanceof Array&&a.dct instanceof Object&&(d=a.evt,N=a.dct,d&&N&&((a=(c.ue.ssw("eelsts")||{}).val)&&"unk"===a&&m(),c.ue.ssw("eeldata","{}"),c.ue.ssw("eelsts","unk")))}z.event.replay(function(a){a[3]=a[3]||{};a[3].n=1;k.apply(this,a)});z.onSushiUnload.replay(function(a){A(a[0])});z.onSushiFlush.replay(function(a){y(a[0])})}})();z.attach("beforeunload",
x);z.attach("pagehide",x);z._cmps=p;z.event=k;z.event.reset=function(){R=0};z.onSushiUnload=A;z.onSushiFlush=y;try{b.P&&b.P.register&&b.P.register("sushi-client",t)}catch(e){c.ueLogError(e,{logLevel:"WARN"})}a("ld","ue_sushi_v1",{wb:1})},"Nxs-JS-Client")(ue_csm,window);