(function(g){var k=window.AmazonUIPageJS||window.P,n=k._namespace||k.attributeErrors,d=n?n("TwisterHardlinesDetailPageAsset"):k;d.guardFatal?d.guardFatal(g)(d,window):d.execute(function(){g(d,window)})})(function(g,k,n){g.when("A","jQuery","atf").execute(function(d,b){d.on.ready(function(){function c(a,c,d,e,f){b(a).slideToggle(300);b(c).slideToggle(300);b(d).toggleClass("tmmShowPrompt tmmHidePrompt");b(e).toggleClass("tmmShowPrompt tmmHidePrompt");b(f).toggleClass("rotate")}function f(a){a.position();
a.width();b(".swatchElement");a.find(".swatchElement").each(function(){b(this).attr("data-width",b(this).width())});b("#formats").find(".a-row").removeClass("nonJSFormats")}function a(){var a=b("#formats"),c=a.width()-40,d=0;a.find(".swatchElement").each(function(){b(this).is(":visible")&&(d+=b(this).width())});d>c?b(a.find(".swatchElement:visible").get().reverse()).each(function(){var a=0,e=!1;b(this).find(".format").hasClass("a-button-selected")?(a=b(this).prev(".swatchElement").width(),e=b(this).prev(".swatchElement").is(":hidden"),
b(this).prev(".swatchElement").hide()):(a=b(this).width(),e=b(this).is(":hidden"),b(this).hide());e||(d-=a);return d>c}):d<c&&a.find(".swatchElement").each(function(){if(b(this).is(":hidden"))return b(this).attr("data-width")<=c-d&&b(this).show(),!1})}var e=0,h=0,l,m=function(a){"undefined"!=typeof a&&(l=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){m(k.DPClientLogger)}):g.when("DPClientLogger").execute(m);d.declarative("tmm-see-more-editions-click",
["click"],function(a){var e=a.data,f=e.metabindingUrl;if(a.$target.hasClass("a-link-expander")||a.$target.parent().hasClass("a-link-expander")){var e=e.metabindingPlaceHolder,g="#metabinding_row_top_"+e,h="#metabinding_row_bottom_"+e,l="#editionsSeePrompt_"+e,m="#editionsHidePrompt_"+e,n="#editionsIcon_"+e,p="isAjaxComplete_"+e,q="isAjaxInProgress_"+e;a="#tmmSpinnerDiv_"+e;var C=d.state("mediamatrix-state"),e=C["url_"+e].replace(/&amp;/g,"&");b("#formats .tmmErrorClass").hide();"1"===C[p]||"1"===
C[q]?c(g,h,l,m,n):(d.ajax(e,{method:"get",success:function(){C[p]="1";d.state("mediamatrix-state",C);c(g,h,l,m,n)},indicator:b(a),error:function(){b($tmmErrorDiv).show();C[q]="0";d.state("mediamatrix-state",C)}}),C[q]="1",d.state("mediamatrix-state",C))}else"#"!==f&&(k.location=f)});if(0<b("#formats > .a-link-expander").length){var n=k.ue;n&&n.count&&n.count("mediaMatrixExpanderPresent",1)}b("#formats > .a-link-expander").click(function(){c("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt",
"#formatsIcon");if(!h){var a=k.ue;a&&a.count&&a.count("mediaMatrixExpanderClicked",1);h=1}l&&b("#twister").is(":visible")&&!e&&(l.logImpression("tmm-show-more-formats-viewed"),e=1)});var n=d.state("mediamatrix-state"),C="1";"undefined"!==typeof n&&"undefined"!==typeof n.showHybridMediaMatrix&&"1"===n.showHybridMediaMatrix?C="0":"undefined"!==typeof n&&"undefined"!==typeof n.isDvdWeblabEnabled&&"1"===n.isDvdWeblabEnabled&&(C="0");"1"===C&&(b("#formats.responsive").each(function(){f(b(this))}),a(),
d.on("resize",a));b("#formats .unselected .format").mouseenter(function(){b(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){b(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});b("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})});g.when("A","jQuery","a-dropdown").execute(function(d,b,c){function f(a){return a?a.replace(/&#0/g,"&#"):undef}
function a(a){for(var b=a.getOptions(),b=b?b.size():0,c=1;c<b;c++)a.removeOption(1)}function e(a,c){var d=a.getOption(0),e=d.info()[0];d.remove();b.each(c,function(b,c){a.addOption({text:v[f(c)],value:c,css_class:"dropdownAvailable"},1)});a.addOption(e,0);a.val(e.value)}function g(b){A=b.value;a(w);"-1"!==A&&(l(),e(w,Object.keys(C[f(A)])))}function l(){Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),
d=c.length;return function(e){if("object"!==typeof e&&("function"!==typeof e||null===e))throw new TypeError("Object.keys called on non-object");var f=[],g;for(g in e)a.call(e,g)&&f.push(g);if(b)for(g=0;g<d;g++)a.call(e,c[g])&&f.push(c[g]);return f}}())}function m(a){B=a.value;"-1"!==B&&"-1"!==A&&(k.location=z[C[f(A)][f(B)]])}function n(a){a=a.value;"-1"!==a&&(k.location=z[f(a)])}var C,r=d.state("dcdMetaData");if(r){var z=r.asinToDetailPageURLMap,v=r.truncatedValuesMap,x=r.dimensionKeys,u=x[0],A=-1,
B=-1,w;2===x.length?(C=r.doubleValuesToAsinMap,r=x[1],x=c.getSelect("native_dcd_dropdown_"+u),w=c.getSelect("native_dcd_dropdown_"+r),x.setValue("-1"),w.setValue("-1"),a(w),d.on("a:dropdown:selected:"+u,g),d.on("a:dropdown:selected:"+r,m)):(x=c.getSelect("native_dcd_dropdown_"+u),(c=r.selectedAsin)?x.setValue(c):x.setValue("-1"),d.on("a:dropdown:selected:asin-redirect",n))}})});
/* ******** */
(function(g){var k=window.AmazonUIPageJS||window.P,n=k._namespace||k.attributeErrors,d=n?n("PInfoHardlinesDetailPageAsset"):k;d.guardFatal?d.guardFatal(g)(d,window):d.execute(function(){g(d,window)})})(function(g,k,n){g.when("A","jQuery","atf").execute(function(d,b,c){function f(){var a=parseInt(b("#byline").width()),c=0;b("#byline .author").each(function(){b(this).is(".notFaded")&&(c+=b(this).outerWidth())});c+=b("#byline .more").outerWidth();if(c>a){var d=b("#byline .author.notFaded").length;b(b("#byline .author.notFaded").get().reverse()).each(function(f){c>
a&&f<d-1&&(f=b(this).width(),b(this).removeClass("notFaded"),b(this).fadeOut(10,function(){b(this).hide()}),c-=f,b("#byline .moreCount").html(b("#byline .author").length-b("#byline .author.notFaded").length),b("#byline .more").addClass("notFaded").fadeIn(10))})}else if(c<a&&b("#byline .author.notFaded").length<b("#byline .author").length){var f=a-c;b("#byline .author").each(function(){if(!b(this).hasClass("notFaded")){var a=b(this).outerWidth();a<=f?(f-=a,b(this).addClass("notFaded").fadeIn(10),a=
b("#byline .author").length-b("#byline .author.notFaded").length,0===a?b("#byline .more").removeClass("notFaded").fadeOut(10):(b("#byline .moreCount").html(a),b("#byline .more").addClass("notFaded").fadeIn(10))):f=0}})}}b("#byline .showMoreLink").click(function(){b("#byline .author").each(function(){b(this).hasClass("notFaded")||b(this).addClass("notFaded").fadeIn(0);b("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});b("#byline .contributorNameID").mouseenter(function(){var a=b(this).attr("data-asin"),
c={},f="isAjaxComplete_"+a,g="isAjaxInProgress_"+a,k=d.state("popoverImage-state");c.entityID=a;"1"!==k[f]&&"1"!==k[g]&&(b.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:c,dataType:"html",timeout:1E3,success:function(c){b("#contributorImageContainer"+a).get(0).innerHTML=c;k[f]="1";d.state("popoverImage-state",k)},error:function(){k[g]="0";d.state("popoverImage-state",k)}}),k[g]="1",d.state("popoverImage-state",k))});(function(a){var c=parseInt(a.width()),
d=parseInt(a.find(".more").outerWidth()),f=0;b("#byline .author").each(function(){b(this).is(".notFaded")&&(f+=b(this).outerWidth())});b("#byline .more").attr("data-width",d);var g=c-d;if(g>f)a.find(".author").each(function(){var a=b(this).index();3<=parseInt(a)?(a=b(this).outerWidth(),b(this).attr("data-width",a),a<g?(g-=a,b(this).addClass("notFaded"),b(this).fadeIn("slow")):(g=0,b(this).fadeOut("slow"))):(a=b(this).outerWidth(),b(this).attr("data-width",a),g-=a)});else{var k=b("#byline .author.notFaded").length;
b(b("#byline .author.notFaded").get().reverse()).each(function(a){g<f&&a<k-1&&(a=b(this).outerWidth(),f-=a,b(this).fadeOut("slow").removeClass("notFaded"))})}c=a.find(".author").length-a.find(".author.notFaded").length;0<c&&(a.find(".moreCount").html(c),a.find(".more").fadeIn("slow"),a.find(".more").addClass("notFaded"))})(d.$("#byline"));b(k).resize(function(){f()})});g.when("A","jQuery","atf").execute(function(d,b,c){function f(){var a=parseInt(b("#bylineInfo").width()),c=0;b("#bylineInfo .author").each(function(){b(this).is(".notFaded")&&
(c+=b(this).outerWidth())});c+=b("#bylineInfo .more").outerWidth();if(c>a){var d=b("#bylineInfo .author.notFaded").length;b(b("#bylineInfo .author.notFaded").get().reverse()).each(function(f){c>a&&f<d-1&&(f=b(this).width(),b(this).removeClass("notFaded"),b(this).fadeOut(10,function(){b(this).hide()}),c-=f,b("#bylineInfo .moreCount").html(b("#bylineInfo .author").length-b("#bylineInfo .author.notFaded").length),b("#bylineInfo .more").addClass("notFaded").fadeIn(10))})}else if(c<a&&b("#bylineInfo .author.notFaded").length<
b("#bylineInfo .author").length){var f=a-c;b("#bylineInfo .author").each(function(){if(!b(this).hasClass("notFaded")){var a=b(this).outerWidth();a<=f?(f-=a,b(this).addClass("notFaded").fadeIn(10),a=b("#bylineInfo .author").length-b("#bylineInfo .author.notFaded").length,0===a?b("#bylineInfo .more").removeClass("notFaded").fadeOut(10):(b("#bylineInfo .moreCount").html(a),b("#bylineInfo .more").addClass("notFaded").fadeIn(10))):f=0}})}}b("#bylineInfo .showMoreLink").click(function(){b("#bylineInfo .author").each(function(){b(this).hasClass("notFaded")||
b(this).addClass("notFaded").fadeIn(0);b("#bylineInfo .more").removeClass("notFaded").fadeOut(0)});return!1});b("#bylineInfo .contributorNameID").mouseenter(function(){var a=b(this).attr("data-asin"),c={},f="isAjaxComplete_"+a,g="isAjaxInProgress_"+a,k=d.state("popoverImage-state");c.entityID=a;"1"!==k[f]&&"1"!==k[g]&&(b.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:c,dataType:"html",timeout:1E3,success:function(c){b("#contributorImageContainer"+a).get(0).innerHTML=
c;k[f]="1";d.state("popoverImage-state",k)},error:function(){k[g]="0";d.state("popoverImage-state",k)}}),k[g]="1",d.state("popoverImage-state",k))});(function(a){var c=parseInt(a.width()),d=parseInt(a.find(".more").outerWidth()),f=0;b("#bylineInfo .author").each(function(){b(this).is(".notFaded")&&(f+=b(this).outerWidth())});b("#bylineInfo .more").attr("data-width",d);var g=c-d;if(g>f)a.find(".author").each(function(){var a=b(this).index();3<=parseInt(a)?(a=b(this).outerWidth(),b(this).attr("data-width",
a),a<g?(g-=a,b(this).addClass("notFaded"),b(this).fadeIn("slow")):(g=0,b(this).fadeOut("slow"))):(a=b(this).outerWidth(),b(this).attr("data-width",a),g-=a)});else{var k=b("#bylineInfo .author.notFaded").length;b(b("#bylineInfo .author.notFaded").get().reverse()).each(function(a){g<f&&a<k-1&&(a=b(this).outerWidth(),f-=a,b(this).fadeOut("slow").removeClass("notFaded"))})}c=a.find(".author").length-a.find(".author.notFaded").length;0<c&&(a.find(".moreCount").html(c),a.find(".more").fadeIn("slow"),a.find(".more").addClass("notFaded"))})(d.$("#bylineInfo"));
b(k).resize(function(){f()})});g.when("A","jQuery").register("product-description-fix",function(d,b){return{fixTableIssue:function(){b("#productDescription .productDescriptionWrapper table").each(function(){var c=b(this).attr("width");"undefined"!==typeof c?b(this).css("width",c):b(this).css("width","auto")})}}})});
/* ******** */
(function(g){var k=window.AmazonUIPageJS||window.P,n=k._namespace||k.attributeErrors,d=n?n("OffersHardlinesDetailPageAsset"):k;d.guardFatal?d.guardFatal(g)(d,window):d.execute(function(){g(d,window)})})(function(g,k,n){g.when("A","jQuery","atf").register("accordionBuyBoxJS",function(d,b,c){var f={updateCssClass:function(a){var c=b("#rbbContainer");c.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");c.find(".selected .offer-price").removeClass("a-color-price").addClass("a-color-secondary");
a.parents(".rbbSection").removeClass("unselected").addClass("selected");a.parents(".rbbSection").toggleClass("dp-accordion-active",500);a.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");a.find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price");b("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price")},animate:function(a){var c=b("#rbbContainer"),d=a.attr("id"),
f,g;c.find(".rbbSection").each(function(a,c){b(c).find(".rbbHeader")[0].id==d?f=b(c):b(c).hasClass("selected")&&(g=b(c))});g.find(".rbbContent").slideUp(500,function(){g.removeClass("selected").addClass("unselected");g.toggleClass("dp-accordion-active",500)});f.find(".rbbContent").slideDown(500);b.browser.msie&&7==parseInt(b.browser.version,10)&&(f.find(".rbbContent").css("display","inline"),setTimeout(function(){f.find(".rbbContent").css("display","block")},505))},oneClickJS:function(){b("#one-click-button, #one-click-button-ubb").click(function(){var a=
"https://"+k.location.host+b("#addToCart").attr("action");b("#addToCart").attr("action",a);return!0})},usedBuyBoxJS:function(){b("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var a=b("#addToCart"),c=a.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");a.attr("action",c);return!0});g.when("a-popover").execute(function(a){var c=b("#usedItemConditionInfoLink"),f=a.create(c,{width:250,position:"triggerBottom",activate:d.capabilities.touch?
"onmousemove":"onclick",closeButton:!1,popoverLabel:"Used condition details",name:"usedItemConditionDetailsPopover",dataStrategy:"preload"});c.mouseleave(function(){f.hide()})})},initialize:function(){b(".rbbHeaderLink").attr("href","javascript:void(0);");b("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();b("#rbbContainer .rbbSection .rbbHeader").click(function(a){b(a.target);a=b(this);var c=a.hasClass("rbbHeader")?a:a.parents(".rbbHeader");if(c.parents(".rbbSection").hasClass("selected"))return!1;
a=b("#rbbContainer .rbbSection.selected .rbbHeader").attr("id");var g=c.attr("id");f.updateCssClass(c);b("#abbWrapper [id^=mbb-offeringID-]").each(function(){this.checked=!1});c=b(this);f.animate(c);d.trigger("buybox:accordion:changed",g,a);return!0});f.oneClickJS();f.usedBuyBoxJS()}};return f})});
/* ******** */
(function(a){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,b=d?d("DetailPagePromotionalBundleAssets"):c;b.guardFatal?b.guardFatal(a)(b,window):b.execute(function(){a(b,window)})})(function(a,c,d){a.when("A","ready").execute("kbpMobileExpander",function(b){var a=b.$;a(".pb-bundle-section-expander").click(function(b){a(".pb-bundle-mobile-box").removeClass("aok-hidden");a(".pb-bundle-expander-box").addClass("aok-hidden")})})});
/* ******** */
